### ISSUE TITLE
False positives? (marks many functions that are definitely used)

### ISSUE THREAD

**Issue by PragTob** [hauleth/mix_unused#39] opened 2022-07-27 11:20 UTC
👋 

Hi there, and thanks for your work on this and general OSS contributions. I tried this out on a bigger properitary code base, so sadly can't share it to reproduce.

But what I found is that it reports way too many cases. I wonder why that is.

It sometimes works. It sometimes doesn't.

## Background

```
➜  git:(mix-unused-code) ✗ elixir -v
Erlang/OTP 25 [erts-13.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.13.4 (compiled with Erlang/OTP 25)
➜  git:(mix-unused-code) ✗  mix deps | grep unused
* mix_unused 0.4.0 (Hex package) (mix)
  locked at 0.4.0 (mix_unused) 082f6b34
```

It's a Phoenix project, relatively standard with `Project` and `ProjectWeb`. The configuration for unused is:

```
      unused: [
        ignore: [
          {Project.Fixtures, :_, :_},
          {Project.Factory, :_, :_},
          # Make more specific later
          {~r/ProjectWeb\..*View/, :_, :_},
          # yeah it doesn't get the connections from routes to these it seems...
          {~r/ProjectWeb\..*Controller/, :_, :_},
          {ProjectWeb.Router.Helpers, :_, :_},
          {ProjectWeb.Router, :_, :_},
          {ProjectWeb.Gettext, :_, :_},
          {ProjectWeb.Endpoint, :_, :_},
          # te,[praru. see,s weord]
          {~r/ProjectWeb\.ApiDocs.*/, :_, :_},
          {~r/Project\.Scripts.*/, :_, :_},
          {Project.Repo, :_, :_},
          {:_, :__schema__, 2},
          {:_, :__changeset__, 2},
          {:_, :__enums__, 2},
          {:_, :__enum_map__, 2},
          {FixturesSupport, :_, :_}
        ]
      ]
```

I only add the compiler in the `dev` environment and then run `mix compile --force`.

### One case of unused function that is definitely used

```
hint: Project.Billing.fetch_bank_account_for_wise_from_withdrawal_method/1 is unused
    lib/project/billing.ex:86
```

This function is called in 2 places. For instance: `Project.PaymentProcessor.Service.PayContractorInvoice` - it's inside a big `with` statement within the `call` function.

```
{:ok, bank_account} <-
           Billing.fetch_bank_account_for_wise_from_withdrawal_method(invoice.withdrawal_method_id),
```

Seems like it _should_ be straight forward.

I was worried that it might be a transitive thing, but `Project.PaymentProcessor.Service.PayContractorInvoice.call/2` is not mentioned as being unused. In fact, a function it uses is even highlighted as "should be private".

So... I'm confused.

### Another unused case where it is definitely used

```
hint: Tiger.Billing.set_user_default_bank_account/2 is unused
    lib/tiger/billing.ex:195
```

That one is used in `Project.Billing.Service.SetUserDefaultBankAccount.call/2` up in a case:

```
    case Billing.set_user_default_bank_account(current_user, bank_account) do
```

🤷 

### Correct unused

In the same module, there are also cases where the library is correct.

```
hint: Project.Billing.list_bank_accounts/0 is unused
    lib/project/billing.ex:36
```

Is indeed unused and can be removed.

### Correct used

It doesn't report on `get_bank_account_by_slug` for instance. And it is correct, that function is indeed used. 

-----------------

Let me know what I could do to help you debug this or debug it myself :)

Thanks for all your work!

![IMG_20190127_140756](https://user-images.githubusercontent.com/606517/181234719-5de4455e-5cf1-479e-8e0c-1d9d0503656a.jpg)

**Comment by PragTob** [comment] 2022-07-27 12:18
Found another interesting thing where it looks at 2 functions (created by macro) and claims both that it should be private and that it is unused:

```
hint: Module,render_body/3 should be private (is not used outside defining module)
    lib/module.ex:6

hint: Module.render_body/3 is unused
    lib/module.ex:6
```

**Comment by justincy** [comment] 2023-05-10 22:00
I have the same problem.

I think this is caused by the logic being used to decide whether a function is called. https://github.com/hauleth/mix_unused/blob/9f0f6563e6676ed35a2ede38145df9f841cf7e9b/lib/mix_unused/analyzers/unused.ex#L28-L34

If I understand that code correctly, it considers a method as called (i.e. used) if:

1. Any method calling it is known to be called
2. It's not in the possibly_uncalled list (which is just a list of all exported methods that aren't ignored)

At first, the second criteria didn't make sense to me. But now I can see that's helpful in making sure we don't consider ignored methods as used (i.e. blindly mark all ignored methods as used so that they don't show up in our unused list).

But there's still a problem. The first criteria relies on the order in which functions are processed. If a function gets processed before any of the methods which call it then it will never meet that first criteria because nothing which calls it is yet known to be used. I think a depth-first-search is being used to avoid this problem but since graphs have cycles we can't really guarantee an order, all we can guarantee is that we visit all nodes in the graph.

I think what needs to happen is for the algorithm to be updated such that when a function is determined to be called we also recursively traverse the subgraph of all functions it calls and mark them as called. That will be expensive the first few times but not so bad after a while because it short-circuits on anything that's already known to be called.

**Comment by hauleth** [comment] 2023-06-15 10:59
It should be fixed with current `master`. Could you guys check out if the fixed version works for you?

**Comment by justincy** [comment] 2023-06-27 17:46
@hauleth I tested `master` and it looks good; it appears to be producing the same results as the PR that I submitted for this issue.

**Closed** 2023-06-27 21:57 UTC

**Comment by justincy** [comment] 2023-06-29 13:54
@hauleth Do you plan on cutting a new release?

**Comment by hauleth** [comment] 2023-06-29 13:55
Yes, I will probably do it today.

**Comment by hauleth** [comment] 2023-06-29 21:23
V0.4.1 is now live
